<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Prueba</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>wilson.otalvaro@doctus.com.co;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>63c729e4-382b-43fc-ae60-29e8a04a4ba5</testSuiteGuid>
   <testCaseLink>
      <guid>d5f329c0-03d3-4943-b9a5-008f5387be34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Avaluos/QA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13273c4c-b1b0-4d71-bb56-0d9709d59e8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b3ff47c-e969-4715-b519-7b031fae1823</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08031b21-d11f-4b7b-a500-63982d51873e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>486e6f71-acd5-439d-b4f4-c3fb209803c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64658205-ad5b-4a38-bf37-4d8b66572349</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7af98371-eb5e-4585-8b21-6d96f742855d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58e01ffd-788c-416f-bf42-d89b9e6b4b87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4ede7ac-5abf-4a5e-91c1-c1c6374a02bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aecb3d0-9898-4391-84ed-2c8c604c8bfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8cac5fe-439f-4c3c-951a-1d62c5b0f3a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb25638f-7dbe-4b62-b269-04544695cc80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4676daf-57e1-4db9-90bb-102de7766a3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87ac09d6-d8dd-4e25-a74c-9cb2d2ad9760</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Avaluos/Test_avaluos</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bccde34-7604-4214-8082-5ce99a60ca85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fecf8c18-768c-4f12-8b9e-6fae7d2b56c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7119fb8-d105-4c98-8d99-ffbb3479b9c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33a88b9d-6c6f-4c52-a4eb-feb09c83d5af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ada2c4d7-857d-47c5-995b-f6ecd175a241</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef3de233-6cd9-467a-b79c-8542faa990a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00541cd1-79f1-49a3-bce9-557198b9e015</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e3105ac-4141-4c3a-9a58-523efaeb071e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1989e057-6d61-4c1f-844b-97b3eddbbf84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52b4fef0-2e6f-4a90-80b2-25a7d4b4134e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d8d9452-2998-4bd2-bbfd-13d32e71925b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>094490b3-b781-4d0e-ab69-b3b94111c9f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41454a1a-8201-497f-8147-8ff465403840</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Calificar/Calificacion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>406bdab7-d9cf-4ce0-8790-9fdbd78f7081</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1735c729-e2ed-4355-a816-0baf7a51ab07</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f417173b-303c-4f94-9c8b-e7b5f8f51885</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegistroUsuarios/RegistroUsuarios</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6e971165-202e-4028-9fa2-4c29e4160c36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RVInmobiliaria</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dd4f1a29-170a-4c71-9724-a0d89de01141</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RvInmobiliariaAdmin/RvInmobiliariaAdmin</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
